# Generated by Django 3.2.4 on 2021-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_intern',
            field=models.BooleanField(default=True),
        ),
    ]
